version: "{build}"

platform:
  - x86
  - x64

clone_folder: c:\gopath\src\github.com\LawrenceWoodman\ddataset

environment:
  GOPATH: c:\gopath

install:
  - choco install mingw -y
  - set PATH=%PATH%;C:\mingw64\bin
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - go test -v ./...
